version: '3'

services:

    db:
        container_name: mysql
        restart: always
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_DATABASE: 'agenda-petshop'
            MYSQL_ROOT_PASSWORD: 'mysql'
        networks: 
            - db_connection
        ports: 
            - '3306:3306'

    webapp:
        build: 
            dockerfile: Dockerfile
            context: ./
        ports: 
            - "3000:3000"
        volumes: 
            - ./:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
        environment: 
            MYSQL_HOST: db
            MYSQL_ROOT_PASSWORD: 'mysql'
        links: 
            - db
        networks: 
            - db_connection
        depends_on: 
            - db
        
    adminer:
        image: adminer
        ports: 
           - 8080:8080
        links: 
            - db
        networks: 
            - db_connection

networks: 
    db_connection:
        driver: 'bridge'