version: '3'

services:
    
    db:
        container_name: mysql
        restart: always
        image: mysql
        environment: 
            MYSQL_DATABASE: 'agenda-petshop'
            MYSQL_ROOT_PASSWORD: 'mysql'
        ports: 
            - '3306:3306'
        
    adminer:
        image: adminer
        ports: 
           - 8080:8080